(source gnu)
(source melpa)

;; general
(depends-on "flycheck-cask")
(depends-on "use-package")
(depends-on "auto-complete")
(depends-on "exec-path-from-shell")
(depends-on "flx-ido")
(depends-on "whitespace-cleanup-mode")
(depends-on "column-enforce-mode")
(depends-on "smex")
(depends-on "rainbow-delimiters")

;; c
(depends-on "cc-mode")

;; ocaml
(depends-on "tuareg")
(depends-on "merlin")
(depends-on "flycheck-ocaml")

;; rust
(depends-on "rust-mode")
(depends-on "flycheck-rust")
